/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import acm.program.*;
import acm.util.*;
import java.applet.AudioClip;

import java.io.*;
import java.util.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.sound.sampled.*;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author Lu Family
 */

public class jTunes extends javax.swing.JFrame {
    
    String song;
    public static String songz;
    File Song;
    Clip clip = null;
    public static double amount;
    String song_det;
    String prev_song_det;

    /**
     * Creates new form jTunes
     */
    public jTunes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Songs", "Radioactive", "Rude", "See You Again", "Shake It Off", "Thinking Out Loud" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lyrics", "Radioactive", "Rude", "See You Again", "Shake It Off", "Thinking Out Loud" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton1.setText("PURCHASE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jToggleButton1.setText("PLAY/STOP");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("COVER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        Object selected = jComboBox1.getSelectedItem();
        if(selected.toString().equals("Radioactive")){
            song = "C:\\Users\\Lu Family\\Desktop\\Ervin's Files\\DLSU\\Term 7\\CPEPROG\\PROJECT\\Music Files\\Radioactive.wav";
            songz = "Radioactive";
            
            ImageIcon icon= new ImageIcon("C:\\Users\\Lu Family\\Desktop\\Ervin's Files\\DLSU\\Term 7\\CPEPROG\\PROJECT\\Album Covers\\Radioactive.jpg"); 
            Image img = icon.getImage(); 
            Image newimg = img.getScaledInstance(230, 310,  java.awt.Image.SCALE_SMOOTH);  
            icon = new ImageIcon(newimg);
            jLabel1.setIcon(icon);
            
            amount = 5.00;
            
            song_det = "C:\\Users\\Lu Family\\Desktop\\Ervin's Files\\DLSU\\Term 7\\CPEPROG\\PROJECT\\Song Details\\Radioactive.txt";
            
            try {
			File file = new File("C:\\Users\\Lu Family\\Desktop\\Ervin's Files\\DLSU\\Term 7\\CPEPROG\\PROJECT\\Song Details\\Radioactive.txt");
			FileReader fileReader = new FileReader(file);
			BufferedReader bufferedReader = new BufferedReader(fileReader);
			StringBuffer stringBuffer = new StringBuffer();
			String line;
			while ((line = bufferedReader.readLine()) != null) 
                        {
				stringBuffer.append(line);
				stringBuffer.append("\n");
			}
                        jTextArea1.setText(stringBuffer.toString());
			fileReader.close();
			//System.out.println("Contents of file:");      //FOR ECHOING
			//System.out.println(stringBuffer.toString());
		} catch (IOException e) {
			e.printStackTrace();
                }
            
        }
        
        else if(selected.toString().equals("Rude")){
            song = "C:\\Users\\Lu Family\\Desktop\\Ervin's Files\\DLSU\\Term 7\\CPEPROG\\PROJECT\\Music Files\\Rude.wav";
            songz = "Rude";
            
            ImageIcon icon= new ImageIcon("C:\\Users\\Lu Family\\Desktop\\Ervin's Files\\DLSU\\Term 7\\CPEPROG\\PROJECT\\Album Covers\\Rude.jpg"); 
            Image img = icon.getImage(); 
            Image newimg = img.getScaledInstance(224, 224,  java.awt.Image.SCALE_SMOOTH);  
            icon = new ImageIcon(newimg);
            jLabel1.setIcon(icon);
            
            amount = 5.00;
            
            song_det = "C:\\Users\\Lu Family\\Desktop\\Ervin's Files\\DLSU\\Term 7\\CPEPROG\\PROJECT\\Song Details\\Rude.txt";
            
            try {
			File file = new File("C:\\Users\\Lu Family\\Desktop\\Ervin's Files\\DLSU\\Term 7\\CPEPROG\\PROJECT\\Song Details\\Rude.txt");
			FileReader fileReader = new FileReader(file);
			BufferedReader bufferedReader = new BufferedReader(fileReader);
			StringBuffer stringBuffer = new StringBuffer();
			String line;
			while ((line = bufferedReader.readLine()) != null) 
                        {
				stringBuffer.append(line);
				stringBuffer.append("\n");
			}
                        jTextArea1.setText(stringBuffer.toString());
			fileReader.close();
			//System.out.println("Contents of file:");      //FOR ECHOING
			//System.out.println(stringBuffer.toString());
		} catch (IOException e) {
			e.printStackTrace();
                }
        }
        
        else if(selected.toString().equals("See You Again")){
            song = "C:\\Users\\Lu Family\\Desktop\\Ervin's Files\\DLSU\\Term 7\\CPEPROG\\PROJECT\\Music Files\\See You Again.wav";
            songz = "See You Again";
            
            ImageIcon icon= new ImageIcon("C:\\Users\\Lu Family\\Desktop\\Ervin's Files\\DLSU\\Term 7\\CPEPROG\\PROJECT\\Album Covers\\See You Again.jpg"); 
            Image img = icon.getImage(); 
            Image newimg = img.getScaledInstance(224, 224,  java.awt.Image.SCALE_SMOOTH);  
            icon = new ImageIcon(newimg);
            jLabel1.setIcon(icon);
            
            amount = 10.00;
            
            song_det = "C:\\Users\\Lu Family\\Desktop\\Ervin's Files\\DLSU\\Term 7\\CPEPROG\\PROJECT\\Song Details\\See You Again.txt";
            
            try {
			File file = new File("C:\\Users\\Lu Family\\Desktop\\Ervin's Files\\DLSU\\Term 7\\CPEPROG\\PROJECT\\Song Details\\See You Again.txt");
			FileReader fileReader = new FileReader(file);
			BufferedReader bufferedReader = new BufferedReader(fileReader);
			StringBuffer stringBuffer = new StringBuffer();
			String line;
			while ((line = bufferedReader.readLine()) != null) 
                        {
				stringBuffer.append(line);
				stringBuffer.append("\n");
			}
                        jTextArea1.setText(stringBuffer.toString());
			fileReader.close();
			//System.out.println("Contents of file:");      //FOR ECHOING
			//System.out.println(stringBuffer.toString());
		} catch (IOException e) {
			e.printStackTrace();
                }
        }
         
        else if(selected.toString().equals("Shake It Off")){
            song = "C:\\Users\\Lu Family\\Desktop\\Ervin's Files\\DLSU\\Term 7\\CPEPROG\\PROJECT\\Music Files\\Shake It Off.wav";
            songz = "Shake It Off";
            
            ImageIcon icon= new ImageIcon("C:\\Users\\Lu Family\\Desktop\\Ervin's Files\\DLSU\\Term 7\\CPEPROG\\PROJECT\\Album Covers\\Shake It Off.jpg"); 
            Image img = icon.getImage(); 
            Image newimg = img.getScaledInstance(224, 224,  java.awt.Image.SCALE_SMOOTH);  
            icon = new ImageIcon(newimg);
            jLabel1.setIcon(icon);
            
            amount = 10.00;
            
            song_det = "C:\\Users\\Lu Family\\Desktop\\Ervin's Files\\DLSU\\Term 7\\CPEPROG\\PROJECT\\Song Details\\Shake It Off.txt";
            
            try {
			File file = new File("C:\\Users\\Lu Family\\Desktop\\Ervin's Files\\DLSU\\Term 7\\CPEPROG\\PROJECT\\Song Details\\Shake It Off.txt");
			FileReader fileReader = new FileReader(file);
			BufferedReader bufferedReader = new BufferedReader(fileReader);
			StringBuffer stringBuffer = new StringBuffer();
			String line;
			while ((line = bufferedReader.readLine()) != null) 
                        {
				stringBuffer.append(line);
				stringBuffer.append("\n");
			}
                        jTextArea1.setText(stringBuffer.toString());
			fileReader.close();
			//System.out.println("Contents of file:");      //FOR ECHOING
			//System.out.println(stringBuffer.toString());
		} catch (IOException e) {
			e.printStackTrace();
                }
        }
        
        else if(selected.toString().equals("Thinking Out Loud")){
            song = "C:\\Users\\Lu Family\\Desktop\\Ervin's Files\\DLSU\\Term 7\\CPEPROG\\PROJECT\\Music Files\\Thinking Out Loud.wav";
            songz = "Thinking Out Loud";
            
            ImageIcon icon= new ImageIcon("C:\\Users\\Lu Family\\Desktop\\Ervin's Files\\DLSU\\Term 7\\CPEPROG\\PROJECT\\Album Covers\\Thinking Out Loud.jpg"); 
            Image img = icon.getImage(); 
            Image newimg = img.getScaledInstance(224, 224,  java.awt.Image.SCALE_SMOOTH);  
            icon = new ImageIcon(newimg);
            jLabel1.setIcon(icon);
            
            amount = 15.00;
            
            song_det = "C:\\Users\\Lu Family\\Desktop\\Ervin's Files\\DLSU\\Term 7\\CPEPROG\\PROJECT\\Song Details\\Thinking Out Loud.txt";
            
            try {
			File file = new File("C:\\Users\\Lu Family\\Desktop\\Ervin's Files\\DLSU\\Term 7\\CPEPROG\\PROJECT\\Song Details\\Thinking Out Loud.txt");
			FileReader fileReader = new FileReader(file);
			BufferedReader bufferedReader = new BufferedReader(fileReader);
			StringBuffer stringBuffer = new StringBuffer();
			String line;
			while ((line = bufferedReader.readLine()) != null) 
                        {
				stringBuffer.append(line);
				stringBuffer.append("\n");
			}
                        jTextArea1.setText(stringBuffer.toString());
			fileReader.close();
			//System.out.println("Contents of file:");      //FOR ECHOING
			//System.out.println(stringBuffer.toString());
		} catch (IOException e) {
			e.printStackTrace();
                }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:

        JToggleButton btn = (JToggleButton) evt.getSource();
        if (btn.isSelected()) 
        {
            //JOptionPane.showMessageDialog(null, "PLEASE DOWNLOAD PLUGIN", "SORRY", JOptionPane.WARNING_MESSAGE);
            Song = new File(song);
            PlaySound(Song);
        }
        
        else
        {
            StopSound(Song);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null, "Thank you for buying\nRadioactive by Imagine Dragons", "RECEIPT", JOptionPane.INFORMATION_MESSAGE);
        Receipt receipt = new Receipt();
        receipt.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        Object selected = jComboBox2.getSelectedItem();
        if(selected.toString().equals("Radioactive"))
        {
            try {
			File file = new File("C:\\Users\\Lu Family\\Desktop\\Ervin's Files\\DLSU\\Term 7\\CPEPROG\\PROJECT\\Lyrics\\Radioactive.txt");
			FileReader fileReader = new FileReader(file);
			BufferedReader bufferedReader = new BufferedReader(fileReader);
			StringBuffer stringBuffer = new StringBuffer();
			String line;
			while ((line = bufferedReader.readLine()) != null) 
                        {
				stringBuffer.append(line);
				stringBuffer.append("\n");
			}
                        jTextArea1.setText(stringBuffer.toString());
			fileReader.close();
			//System.out.println("Contents of file:");      //FOR ECHOING
			//System.out.println(stringBuffer.toString());
		} catch (IOException e) {
			e.printStackTrace();
                }
        }
        
        else if(selected.toString().equals("Rude"))
        {
            try {
			File file = new File("C:\\Users\\Lu Family\\Desktop\\Ervin's Files\\DLSU\\Term 7\\CPEPROG\\PROJECT\\Lyrics\\Rude.txt");
			FileReader fileReader = new FileReader(file);
			BufferedReader bufferedReader = new BufferedReader(fileReader);
			StringBuffer stringBuffer = new StringBuffer();
			String line;
			while ((line = bufferedReader.readLine()) != null) 
                        {
				stringBuffer.append(line);
				stringBuffer.append("\n");
			}
                        jTextArea1.setText(stringBuffer.toString());
			fileReader.close();
			//System.out.println("Contents of file:");      //FOR ECHOING
			//System.out.println(stringBuffer.toString());
		} catch (IOException e) {
			e.printStackTrace();
                }
        }
        
        else if(selected.toString().equals("See You Again"))
        {
            try {
			File file = new File("C:\\Users\\Lu Family\\Desktop\\Ervin's Files\\DLSU\\Term 7\\CPEPROG\\PROJECT\\Lyrics\\See You Again.txt");
			FileReader fileReader = new FileReader(file);
			BufferedReader bufferedReader = new BufferedReader(fileReader);
			StringBuffer stringBuffer = new StringBuffer();
			String line;
			while ((line = bufferedReader.readLine()) != null) 
                        {
				stringBuffer.append(line);
				stringBuffer.append("\n");
			}
                        jTextArea1.setText(stringBuffer.toString());
			fileReader.close();
			//System.out.println("Contents of file:");      //FOR ECHOING
			//System.out.println(stringBuffer.toString());
		} catch (IOException e) {
			e.printStackTrace();
                }
        }
        
        else if(selected.toString().equals("Shake It Off"))
        {
            try {
			File file = new File("C:\\Users\\Lu Family\\Desktop\\Ervin's Files\\DLSU\\Term 7\\CPEPROG\\PROJECT\\Lyrics\\Shake It Off.txt");
			FileReader fileReader = new FileReader(file);
			BufferedReader bufferedReader = new BufferedReader(fileReader);
			StringBuffer stringBuffer = new StringBuffer();
			String line;
			while ((line = bufferedReader.readLine()) != null) 
                        {
				stringBuffer.append(line);
				stringBuffer.append("\n");
			}
                        jTextArea1.setText(stringBuffer.toString());
			fileReader.close();
			//System.out.println("Contents of file:");      //FOR ECHOING
			//System.out.println(stringBuffer.toString());
		} catch (IOException e) {
			e.printStackTrace();
                }
        }
        
        else if(selected.toString().equals("Thinking Out Loud"))
        {
            try {
			File file = new File("C:\\Users\\Lu Family\\Desktop\\Ervin's Files\\DLSU\\Term 7\\CPEPROG\\PROJECT\\Lyrics\\Thinking Out Loud.txt");
			FileReader fileReader = new FileReader(file);
			BufferedReader bufferedReader = new BufferedReader(fileReader);
			StringBuffer stringBuffer = new StringBuffer();
			String line;
			while ((line = bufferedReader.readLine()) != null) 
                        {
				stringBuffer.append(line);
				stringBuffer.append("\n");
			}
                        jTextArea1.setText(stringBuffer.toString());
			fileReader.close();
			//System.out.println("Contents of file:");      //FOR ECHOING
			//System.out.println(stringBuffer.toString());
		} catch (IOException e) {
			e.printStackTrace();
                }
        }
        
        else
        {
            //jTextArea1.setText("");
            prev_song_det = song_det;
            try {
			File file = new File(prev_song_det);
			FileReader fileReader = new FileReader(file);
			BufferedReader bufferedReader = new BufferedReader(fileReader);
			StringBuffer stringBuffer = new StringBuffer();
			String line;
			while ((line = bufferedReader.readLine()) != null) 
                        {
				stringBuffer.append(line);
				stringBuffer.append("\n");
			}
                        jTextArea1.setText(stringBuffer.toString());
			fileReader.close();
			//System.out.println("Contents of file:");      //FOR ECHOING
			//System.out.println(stringBuffer.toString());
		} catch (IOException e) {
			e.printStackTrace();
                }
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed
    
    void PlaySound(File Sound) {
        try {
            clip = AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(Sound));
            clip.start();
            
            //Thread.sleep(clip.getMicrosecondLength()/1000);   //FOR NOT ALLOWING USER TO DO ANYTHING
        } catch(Exception e) {
            System.out.println("ERROR");
        }
    }
    
    void StopSound(File Sound) {
        try 
        {
            clip.stop();
        } catch(Exception e) 
        {
            System.out.println("ERROR");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jTunes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jTunes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jTunes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jTunes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jTunes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
