/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import javax.swing.JOptionPane;

/**
 *
 * @author Lu Family
 */
public class Receipt extends javax.swing.JFrame {
    
    double pay = 0.0;

    /**
     * Creates new form Receipt
     */
    public Receipt() {
        initComponents();
        pay = jTunes.amount;
        jTextField1.setText(String.valueOf(pay));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel1.setText("RECEIPT");

        jLabel2.setText("Amount to be paid:");

        jLabel3.setText("Enter amount:");

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setFont(new java.awt.Font("Tahoma", 3, 23)); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 3, 13)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //double pay = 0;
        double paid = 0;
        double change = 0;  
        String receipt;
        String song;
        String sukli;
        double changes1 = 0;
        double changes2 = 0;
        double changes3 = 0;
        double changes4 = 0;
        double changes5 = 0;
        double changes6 = 0;
        double changes7 = 0;
        double changes8 = 0;
        double changes9 = 0;
        double changes10 = 0;   
        
    try
    {
        pay = jTunes.amount;
        jTextField1.setText(String.valueOf(pay));
        //pay = Double.parseDouble(jTextField1.getText());
        paid = Double.parseDouble(jTextField2.getText());
        
        change = paid - pay;
        
        song = jTunes.songz;
        
        receipt = "You need to pay \t:\t" + pay + 
                  "\n\nAmount you paid \t:\t" + paid + 
                  "\n\nYour change \t\t:\t" + change +
                  "\n\nThank you for buying \t:\t" + song;
        
        jTextArea1.setText(receipt);
        
        while (change > 0.0)
        {
            if (change >= 1000) 
            {
                changes1 = Math.floor(change/1000);
                System.out.println(Math.floor(change/1000) + " - 1000 Php");
                change = change - (Math.floor(change/1000)*1000);
            }
            
            else if (change >= 500) 
            {
                changes2 = Math.floor(change/500);
                System.out.println(Math.floor(change/500) + " - 500 Php");
                change = change - (Math.floor(change/500)*500);
            }
            
            else if (change >= 200) 
            {
                changes3 = Math.floor(change/200);
                System.out.println(Math.floor(change/200) + " - 200 Php");
                change = change - (Math.floor(change/200)*200);
            }
            
            else if (change >= 100) 
            {
                changes4 = Math.floor(change/100);
                System.out.println(Math.floor(change/100) + " - 100 Php");
                change = change - (Math.floor(change/100)*100);
            }
            
            else if (change >= 50) 
            {
                changes5 = Math.floor(change/50);
                System.out.println(Math.floor(change/50) + " - 50 Php");
                change = change - (Math.floor(change/50)*50);
            }
            
            else if (change >= 20) 
            {
                changes6 = Math.floor(change/20);
                System.out.println(Math.floor(change/20) + " - 20 Php");
                change = change - (Math.floor(change/20)*20);
            }
            
            else if (change >= 10) 
            {
                changes7 = Math.floor(change/10);
                System.out.println(Math.floor(change/10) + " - 10 Php");
                change = change - (Math.floor(change/10)*10);
            }
            
            else if (change >= 5) 
            {
                changes8 = Math.floor(change/5);
                System.out.println(Math.floor(change/5) + " - 5 Php");
                change = change - (Math.floor(change/5)*5);
            }
            
            else if (change >= 1) 
            {
                changes9 = Math.floor(change/1);
                System.out.println(Math.floor(change/1) + " - 1 Php");
                change = change - (Math.floor(change/1)*1);
            }
            
            else if (change >= 0.25) 
            {
                changes10 = Math.floor(change/0.25);
                System.out.println(Math.floor(change/0.25) + " Php");
                change = change - (Math.floor(change/0.25)*0.25);
            }
        }   //END WHILE
        
        sukli = changes1 + " - 1000 Php\n" +
                changes2 + " - 500 Php\n" +
                changes3 + " - 200 Php\n" +
                changes4 + " - 100 Php\n" +
                changes5 + " - 50 Php\n" +
                changes6 + " - 20 Php\n" +
                changes7 + " - 10 Php\n" +
                changes8 + " - 5 Php\n" +
                changes9 + " - 1 Php\n" +
                changes10 + " - 0.25 Php";
        
        JOptionPane.showMessageDialog(null, sukli, "Change", JOptionPane.INFORMATION_MESSAGE);
    }
    catch(Exception e)
    {
        System.out.println("ERROR");
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
